copyright = 'Everything is mine'
baseurl = "https://anissL93.github.io"
theme = "PaperMod"

[languages]
  [languages.zh]
    title = "Aniss Lan"
    languageName = "中文"

  [languages.en]
    title = "Aniss Lan"
    languageName = "English"

[params.homeInfoParams]
    Title = "Aniss Lan"
    Content = "A place to record life"

[[params.socialIcons]]
name = "github"
url = "https://github.com/AnissL93"

# [[params.socialIcons]]
# name = "linkin"
# url = "https://github.com/AnissL93"
