---
title: "Deploy a private cloud and messager by nextcloud and frp"
date: 2023-09-24T19:08:04+08:00
draft: true
---

This blog records my experience of deploying Nextcloud and Talk. The basic idea is to first deploy the Nextcloud service on my local PC, and use frp, vps, ningx and a public domain to allow public accessing.

* Prepare
- vps (I use linode). Assume the ip addr is <vps-ip>.
- domain (I use namecheap). Assume the domain is yourdomain.com.
- a local PC (I use an old thinkpad)
* Set up domain
We need to set up a domain pointing to the server. Just goto managing DNS, and add an A record. This is for ipv4 address. Fill in the host, which is the prefix of the domain that will link to your nextcloud login page. I set up something like the following table. The ipv6 part is optional.

| Type        | IP Address      | Host      | TTL       |
|-------------+-----------------+-----------+-----------|
| A record    | <vps-ipv4-addr> | @         | Automatic |
| A record    | <vps-ipv4-addr> | nextcloud | Automatic |
| AAAA record | <vps-ipv6-addr> | @         | Automatic |
| AAAA record | <vps-ipv6-addr> | nextcloud | Automatic |

The nextcloud address will be nextcloud.yourdomain.com.

* Set up vps

* Set up
